spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:statsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: test
    password: test

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.jdbc: DEBUG