server:
  port: 0

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.config.UserActionAvroSerializer

collector:
  kafka:
    topic: stats.user-actions.v1

grpc:
  server:
    port: 9090
    address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://discovery-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${random.int}