server:
  port: 0

grpc:
  server:
    port: 9090
    address: 0.0.0.0

collector:
  kafka:
    topic: stats.user-actions.v1

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: ru.practicum.config.UserActionAvroSerializer
      properties:
        max.block.ms: 5000
        request.timeout.ms: 5000
        delivery.timeout.ms: 10000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    metadata-map:
      grpcPort: ${grpc.server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always