server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 1
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

spring.cloud.openfeign.circuitbreaker.enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always