server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stats}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  sql:
    init:
      mode: always

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10